### ISSUE TITLE
error when installing.

### ISSUE THREAD

**Issue by bwdxbfzco** [geerlingguy/ansible-collection-php#4]
error when installing using ansible-galaxy

ansible-galaxy collection install geerlingguy.php_roles -p ./collections
- downloading role 'collection', owned by 
[WARNING]: - collection was NOT installed successfully: Content has no field named 'owner'
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.

tried to do the git clone, got the folder structure but no files.

**Comment by geerlingguy** [comment]
Hmm... that seems like it would be an Ansible issue—what version of Ansible are you running?

**Comment by Soren90** [comment]
I have the exact same issue. I'm running the latest version: 
➜  ~ apt list ansible                                                                              
Listing... Done
ansible/xenial,xenial,now 2.9.2-1ppa~xenial all [installed]

EDIT: It seems to be caused by some wierd apt bug. when i checked ansible --version it was still version 2.8. I removed ansible from apt and used pip to install the latest version and now it seems to work.

**Comment by geerlingguy** [comment]
Great! Looks like it was just an Ansible issue.
